services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: telemetry_api:latest
    ports:
      - '8080:8080' # ajustez le port hôte:conteneur si nécessaire
    restart: unless-stopped
    networks:
      - open_telemetry
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheusNet
    ports:
      - '9090:9090'
    volumes:
      - ./Configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - 'host.containers.internal:host-gateway'
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - open_telemetry
    depends_on:
      - api
  grafana:
    image: grafana/grafana:latest
    container_name: grafanaNet
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - open_telemetry
    depends_on:
      - prometheus
  jaeger:
    image: jaegertracing/all-in-one:1.74.0
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '9411:9411'
    restart: 'no' # approximates --rm (no restart)
    networks:
      - open_telemetry
    depends_on:
      - api

volumes:
  grafana-storage:
networks:
  open_telemetry:
